<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="59" started-at="2013-11-15T09:25:31Z" finished-at="2013-11-15T09:25:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="59" started-at="2013-11-15T09:25:31Z" finished-at="2013-11-15T09:25:31Z">
      <class name="test.TestEmployeeDetails">
        <test-method status="PASS" signature="testCalcualateAppraisal()[pri:0, instance:test.TestEmployeeDetails@d42d08]" name="testCalcualateAppraisal" duration-ms="36" started-at="2013-11-15T14:55:31Z" finished-at="2013-11-15T14:55:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalcualateAppraisal -->
        <test-method status="FAIL" signature="testCalculateYearlySalary()[pri:0, instance:test.TestEmployeeDetails@d42d08]" name="testCalculateYearlySalary" duration-ms="1" started-at="2013-11-15T14:55:31Z" finished-at="2013-11-15T14:55:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [372000.0] but found [420000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [372000.0] but found [420000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at test.TestEmployeeDetails.testCalculateYearlySalary(TestEmployeeDetails.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculateYearlySalary -->
      </class> <!-- test.TestEmployeeDetails -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
